use LegoInventoryTracker
go


ALTER TABLE WantsSet
DROP CONSTRAINT FK__WantsSet__LegoSe__160F4887 
ALTER TABLE LegoModel
DROP CONSTRAINT FK__LegoModel__SetID__14270015
ALTER TABLE [Contains]
DROP CONSTRAINT FK__Contains__LegoSe__05D8E0BE
ALTER TABLE OwnsSet
DROP CONSTRAINT FK__OwnsSet__LegoSet__1BC821DD

ALTER TABLE LegoSet
DROP CONSTRAINT PK__LegoSet__3214EC2779C643D6


ALTER TABLE LegoSet
ALTER COLUMN ID varchar(20)
