use LegoInventoryTracker
go

ALTER TABLE WantsSet
DROP CONSTRAINT PK__WantsSet__8459D4550AC42328
ALTER TABLE WantsSet
ALTER COLUMN LegoSet varchar(20) NOT NULL
ALTER TABLE WantsSet
ADD FOREIGN KEY (LegoSet) REFERENCES LegoSet(ID)
ALTER TABLE WantsSet
ADD PRIMARY KEY (LegoSet, Username)

ALTER TABLE LegoModel
ALTER COLUMN SetID varchar(20)
ALTER TABLE LegoModel
ADD FOREIGN KEY (SetID) REFERENCES LegoSet(ID)

ALTER TABLE [Contains]
DROP CONSTRAINT PK__Contains__81BBC99B8FAC736F
ALTER TABLE [Contains]
ALTER COLUMN LegoSet varchar(20) NOT NULL
ALTER TABLE [Contains]
ADD FOREIGN KEY (LegoSet) REFERENCES LegoSet(ID)

ALTER TABLE OwnsSet
DROP CONSTRAINT PK__OwnsSet__8459D45531BFA9FC
ALTER TABLE OwnsSet
ALTER COLUMN LegoSet varchar(20) NOT NULL
ALTER TABLE OwnsSet
ADD FOREIGN KEY (LegoSet) REFERENCES LegoSet(ID)
ALTER TABLE OwnsSet
ADD PRIMARY KEY (LegoSet, Username) 